In [2]:
import pandas as pd

# Задача 1.
1. Скачать данные
2. Считать данные с помощью pandas
3. Вывести на экран первые 5 строк

In [3]:
df = pd.read_csv('laptop_price.csv', sep=',', encoding='latin-1')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

### 1.1 Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU

In [4]:
# Вариант 1
# def f(x :str): 
#     return x.split()[0]

# df['Cpu_Company'] = df['Cpu'].apply(f)
# df.head()

# Вариант 2
df['Cpu_Company'] = df['Cpu'].apply(lambda x: x.split()[0])
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel

### 1.2 Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя

In [5]:
def f(x :str):
    x = x.split()
    res = 0
    for i in x:
        if i.endswith('GB') and i[:-2].isdigit():
            res += int(i[:-2])
        elif i.endswith('TB') and i[:-2].isdigit():
            res += int(i[:-2]) * 1024
    return res

df['Memory_Amount'] = df['Memory'].apply(f)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

### 1.3 Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD/SDD/др)

In [6]:
def f(x :str):
    res = []
    if 'HDD' in x:
        res.append('HDD')
    if 'SSD' in x:
        res.append('SSD')
    if not res:
        return 'other'
    return '/'.join(res)

df['Memory_Type'] = df['Memory'].apply(f)
df.head()

# Проверка
# list = ['128GB SSD', '128GB Flash Storage', '256GB SSD', '128GB SSD + 1TB HDD']
# print(f'{f(list[3])}')

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,other
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

### 1.4 Удалить признаки Memory и ScreenResolution

In [7]:
df.drop(columns=['Memory', 'ScreenResolution'], inplace=True)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,other
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

# Задача 2.
### 2.1 Создайте признак SDD, который изначально равен 0

In [8]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,other,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

### 2.2 Поставьте в признаке SDD 1, если ноутбук действительно с типом носителя SDD

In [9]:
df['SSD'] = df['Memory_Type'].apply(lambda x: 1 if 'SSD' in x else 0)
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,other,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1

### 2.3 Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [10]:
df['Weight'] = df['Weight'].str.replace('kg', '')
df['Weight'] = df['Weight'].astype(float)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   laptop_ID      1303 non-null   int64
 1   Company        1303 non-null   object
 2   Product        1303 non-null   object
 3   TypeName       1303 non-null   object
 4   Inches         1303 non-null   float64
 5   Cpu            1303 non-null   object
 6   Ram            1303 non-null   object
 7   Gpu            1303 non-null   object
 8   OpSys          1303 non-null   object
 9   Weight         1303 non-null   float64
 10  Price_euros    1303 non-null   float64
 11  Cpu_Company    1303 non-null   object
 12  Memory_Amount  1303 non-null   int64
 13  Memory_Type    1303 non-null   object
 14  SSD            1303 non-null   int64
dtypes: float64(3), int64(3), object(9)
memory usage: 152.8+ KB

# Задача 3.

In [12]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})

clients.head()

   client_id  laptop_id
0         45        506
1         32        398
2         67        710
3         33        120
4         43       1999

### 3.1 Присоедините к таблице clients данные по ноутбукам через метод joun

In [13]:
client_1 = clients.set_index('laptop_id')
laptop_1 = df.set_index('laptop_ID')

client_1.join(laptop_1, how='inner').head()

,client_id,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
506,45,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256,SSD,1
710,67,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024,HDD,0
120,33,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,1280,HDD/SSD,1

### 3.2 Присоедините к таблице clients данные по ноутбукам через метод merge
Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [14]:
clients.merge(df, left_on='laptop_id', right_on='laptop_ID')

,client_id,laptop_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,45,506,506,Lenovo,ThinkPad L570,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,2.30,911.00,Intel,256,SSD,1
1,67,710,710,Lenovo,IdeaPad 320-15ABR,Notebook,15.6,AMD A12-Series 9720P 3.6GHz,8GB,AMD Radeon R7,Windows 10,2.20,429.00,AMD,1024,HDD,0
2,33,120,120,Dell,Inspiron 7570,Notebook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Nvidia GeForce 940MX,Windows 10,2.16,1130.33,Intel,1280,HDD/SSD,1

# Задача 4.
Составьте несколько сводных таблиц
### 4.1 Найдите среднюю стоимость ноутбуков в зависимости от компании производителя
Отсортируйте от меньшей стоимости к большей

In [35]:
grouped = df.groupby('Company')
grouped.agg({'Price_euros': 'mean'}).sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

### 4.2 Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [38]:
grouped = df.groupby('Cpu_Company')
grouped.agg({'Price_euros': ['min', 'mean', 'max']}).sort_values(('Price_euros', 'mean'))

            Price_euros
                    min         mean     max
Cpu_Company
AMD               199.0   560.638871  2199.0
Samsung           659.0   659.000000   659.0
Intel             174.0  1152.214145  6099.0

### 4.3 Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [39]:
df.pivot_table(index='Cpu_Company', columns='Ram', aggfunc='count', values='Product')

Ram          12GB   16GB  24GB   2GB  32GB    4GB  64GB   6GB    8GB
Cpu_Company
AMD           2.0    3.0   NaN   1.0   NaN   31.0   NaN  13.0   12.0
Intel        23.0  197.0   3.0  21.0  17.0  343.0   1.0  28.0  607.0
Samsung       NaN    NaN   NaN   NaN   NaN    1.0   NaN   NaN    NaN

### 4.4 Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [42]:
df.pivot_table(index='OpSys', columns='Memory_Amount', aggfunc='mean', values='Price_euros', fill_value=0)

Memory_Amount,0,8,16,32,64,128,180,240,256,500,...,768,1024,1088,1152,1280,1536,2048,2176,2304,2560
OpSys,,,,,,,,,,,,,,,,,,,,,
Android,0.0000,0,0.00,0.000000,434.000000,0.000000,0.0,0,0.000000,0.000000,...,0.00,0.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0
Chrome OS,0.0000,0,305.38,412.454545,774.333333,1275.000000,0.0,0,1559.000000,0.000000,...,0.00,0.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0
Linux,0.0000,0,0.00,0.000000,0.000000,490.500000,0.0,0,795.814000,389.056364,...,0.00,581.40129,0,994.000000,0.00000,0.000000,0.000000,0.00,1049.000000,0
Mac OS X,0.0000,0,0.00,0.000000,0.000000,1099.000000,0.0,0,1311.994000,0.000000,...,0.00,0.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0
No OS,0.0000,0,0.00,0.000000,0.000000,362.024000,0.0,0,754.834615,404.675385,...,0.00,540.53960,0,895.666667,1149.00000,0.000000,594.000000,0.00,0.000000,0
Windows 10,755.5575,2249,0.00,270.001471,333.795556,673.385692,1073.5,3100,1218.868329,664.717647,...,1607.96,886.22663,1993,1285.464494,1865.97375,2500.447143,1058.201333,977.95,1590.015556,1849
Windows 10 S,0.0000,0,0.00,0.000000,308.995000,1039.000000,0.0,0,1668.950000,0.000000,...,0.00,0.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0
Windows 7,860.0000,0,0.00,0.000000,0.000000,1320.323333,1199.0,0,1846.466800,924.048333,...,0.00,2899.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0
macOS,0.0000,0,0.00,0.000000,0.000000,1119.315000,0.0,0,1600.370000,0.000000,...,0.00,0.00000,0,0.000000,0.00000,0.000000,0.000000,0.00,0.000000,0

# Задача 5.
Ответьте на несколько вопросов
### 5.1 Ноутбуков каких компаний и с каким процессором больше?

In [52]:
tmp_df = pd.crosstab(index=df['Company'],
            columns=df['Cpu_Company'])
tmp_df

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

In [51]:
tmp_df.max()

Cpu_Company
AMD         25
Intel      297
Samsung      1
dtype: int64

### 5.2 С каким типом памяти и с каким обьемом памяти больше ноутбуков?

In [65]:
pd.crosstab(index=df['Memory_Type'],
            columns=df['Memory_Amount']
            )

Memory_Amount,0,8,16,32,64,128,180,240,256,500,...,768,1024,1088,1152,1280,1536,2048,2176,2304,2560
Memory_Type,,,,,,,,,,,,,,,,,,,,,
HDD,1,0,0,1,0,1,0,0,0,132,...,0,223,1,0,0,0,17,0,0,0
HDD/SSD,0,0,0,0,0,0,0,0,0,0,...,0,0,0,94,73,14,2,2,10,3
SSD,0,1,3,6,1,76,5,1,413,0,...,1,15,0,0,0,0,0,0,0,0
other,9,0,7,38,15,4,0,0,8,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
pd.crosstab(index=df['Memory_Amount'],
            columns=df['Memory_Type']
            ).max()

Memory_Type
HDD        223
HDD/SSD     94
SSD        413
other       38
dtype: int64